export const CLIENT_TOUR_STEPS = [
  {
    id: "welcome",
    type: "welcome",
    title: "Welcome to the Business Health Check",
    body: "This quick tour shows where to take the assessment, review your report, and find recommended resources. You can replay it anytime from the top bar.",
    cta: "Start walkthrough",
  },
  {
    id: "subnav",
    target: '[data-tour="chrome-subnav"]',
    title: "Your workspace navigation",
    body: "Move between Dashboard, Assessment, My Report, Action Plan, and Help Center without leaving the platform shell.",
    radius: 14,
  },
  {
    id: "dashboard",
    target: '[data-tour="nav-dashboard"]',
    navigate: "dashboard",
    title: "Dashboard",
    body: "Your home view shows assessment progress, health snapshot cards, and the next recommended actions.",
    radius: 12,
  },
  {
    id: "assessment",
    target: '[data-tour="nav-assessmentUser"]',
    navigate: "assessmentUser",
    title: "Business Health Assessment",
    body: "Complete the 21 sections at your own pace. Progress saves automatically and you can return anytime.",
    radius: 12,
  },
  {
    id: "reports",
    target: '[data-tour="nav-reports"]',
    navigate: "reports",
    title: "My Report",
    body: "After enough sections are complete, open your category scores, narrative summary, and export options here.",
    radius: 12,
  },
  {
    id: "resources",
    target: '[data-tour="nav-resources"]',
    navigate: "resources",
    title: "Help Center",
    body: "Find worksheets, videos, Academy resources, and consultation options matched to your assessment results.",
    radius: 12,
  },
  {
    id: "theme",
    target: '[data-tour="chrome-theme"]',
    title: "Light and dark mode",
    body: "Switch themes to match your preference. Your choice is saved on this device.",
    radius: 12,
  },
  {
    id: "profile",
    target: '[data-tour="chrome-profile"]',
    title: "Profile and support",
    body: "Give feedback, report bugs, switch to admin view if you have access, or sign out from your profile menu.",
    radius: 12,
  },
];

export const ADMIN_TOUR_STEPS = [
  {
    id: "welcome",
    type: "welcome",
    title: "Welcome to the Admin Portal",
    body: "This tour walks through user management, analytics, report content, assessment CMS, and monitoring tools.",
    cta: "Start walkthrough",
  },
  {
    id: "subnav",
    target: '[data-tour="chrome-subnav"]',
    title: "Admin navigation",
    body: "Overview, Users, Analytics, Content, Monitoring, and Assessment CMS are always one click away.",
    radius: 14,
  },
  {
    id: "overview",
    target: '[data-tour="nav-adminDashboard"]',
    navigate: "adminDashboard",
    title: "Overview",
    body: "See platform activity, recent signups, and quick links into the highest-impact admin workflows.",
    radius: 12,
  },
  {
    id: "users",
    target: '[data-tour="nav-adminUsers"]',
    navigate: "adminUsers",
    title: "User management",
    body: "Search clients, inspect scores and answers, export data, and manage admin or tier1 roles.",
    radius: 12,
  },
  {
    id: "analytics",
    target: '[data-tour="nav-adminAnalytics"]',
    navigate: "adminAnalytics",
    title: "Analytics",
    body: "Review health distribution, section drop-off, question performance, engagement, and at-risk users.",
    radius: 12,
  },
  {
    id: "content",
    target: '[data-tour="nav-adminContent"]',
    navigate: "adminContent",
    title: "Report content",
    body: "Edit the narrative and recommended resources clients see for each category and health state.",
    radius: 12,
  },
  {
    id: "monitoring",
    target: '[data-tour="nav-adminMonitoring"]',
    navigate: "adminMonitoring",
    title: "Monitoring",
    body: "Triage bug reports and product feedback without changing client assessment data.",
    radius: 12,
  },
  {
    id: "profile",
    target: '[data-tour="chrome-profile"]',
    title: "Client preview and support",
    body: "Switch to Client Preview to see the platform as a user, or use feedback and bug report tools from your profile menu.",
    radius: 12,
  },
];
